patches: Add patch to remove abi-tag
ABI_TAG was introduced in upstream:
https://github.com/llvm/llvm-project/commit/67b0b02ec9f2bbc57bf8f0550828d97f460ac11f

These ABI_TAG leads to error:

build/libcxx/origin/libcxx-15.0.0.src/include/__support/musl/xlocale.h:38:74:
error: ‘abi_tag’ attribute applied to extern "C" declaration ‘long long
int wcstoll_’
   38 | wcstoll_l(const wchar_t *__nptr, wchar_t **__endptr, int __base,
locale_t) {

Signed-off-by: Mamta Shukla <mamtashukla555@gmail.com>