Makefile.uk: Use -fpermissive flag
Use -fpermissive flag to allow compiler-rt build

note: (if you use ‘-fpermissive’, G++ will accept your code, but
allowing the use of an undeclared name is deprecated)

build/libcxx/origin/libcxx-15.0.0.src/include/__type_traits/is_same.h:22:72:
error: template argument 1 is invalid
   22 | struct _LIBCPP_TEMPLATE_VIS is_same :
_BoolConstant<__is_same(_Tp, _Up)> { };

Signed-off-by: Mamta Shukla <mamtashukla555@gmail.com>